#!/bin/sh

# Purpose: Compile and run a go file as a script.
# Input: Path to a go file, additional arguments.
# Output: Any output from the go script.
# Side effects: Temp files from compiling.
# Author: Issac Trotts <issac.trotts@gmail.com>

echo_usage() {
    echo 'usage: goscript program.go [args]'
}

if [[ -z "$1" ]]; then
    echo_usage
    exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo_usage
    exit 0
fi

set -o errexit

srcdir=`dirname $1`
progname=`basename $1 .go`
shift

workdir=/tmp/$progname-$RANDOM
object_file=$progname.`goarch ext`

mkdir -p $workdir
# Strip out the shebang line, if any.
sed 's/^#.*$//' $srcdir/$progname.go > $workdir/$progname.go

pushd $workdir > /dev/null
`goarch compiler` -o $object_file $progname.go
`goarch linker` -o $progname $object_file
popd > /dev/null

$workdir/$progname $*

